services:
    frontend:
        build: ./web
        ports:
            - '5173:5173'
        volumes:
            - ./web:/app
            - /app/node_modules
        environment:
            - VITE_API_URL=http://localhost:3000/api
        depends_on:
            - backend

    backend:
        build: ./backend
        ports:
            - '3000:3000'
        volumes:
            - ./backend:/app
            - /app/node_modules
            - ./backend/uploads:/app/uploads

        env_file:
            - ./backend/.env
        environment:
            - DATABASE_URL=postgresql://user:password@db:5432/songIdeasDb?schema=public
            - PORT=3000
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:15-alpine
        platform: linux/arm64
        restart: always
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=songIdeasDb
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U user -d songIdeasDb']
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres-data:
